packages:
  - "."

allowBuilds:
  "@firebase/util": true
  "@parcel/watcher": true
  better-sqlite3: true
  electron: true
  esbuild: true
  keytar: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true

onlyBuiltDependencies:
  - better-sqlite3
  - keytar
  - electron
  - esbuild
  - "@parcel/watcher"
  - lmdb
  - msgpackr-extract
  - protobufjs
  - "@firebase/util"
